# Generated by Django 3.2.8 on 2021-10-29 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=10, null=True)),
                ('overview', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[(1, 'Work'), (2, 'Event'), (3, 'Appointment'), (4, 'Habit')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(default=datetime.date.today)),
                ('endDate', models.DateTimeField(default=datetime.date.today)),
                ('emergency', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
        ),
    ]
