# Generated by Django 3.2.8 on 2021-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211029_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.IntegerField(choices=[(1, 'Work'), (2, 'Event'), (3, 'Appointment'), (4, 'Habit')]),
        ),
    ]
