# Generated by Django 3.2.8 on 2021-10-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='emergency',
            field=models.IntegerField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=1),
        ),
    ]
