# Generated by Django 3.2.8 on 2021-10-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20211011_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
