# Generated by Django 3.2.8 on 2021-10-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='projectName',
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
