# Generated by Django 3.2.8 on 2021-10-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211029_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='overview',
        ),
    ]
