# Generated by Django 3.2.8 on 2021-10-11 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211011_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='endDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todo',
            name='startDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
