# Generated by Django 3.2.8 on 2021-10-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20211011_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
