# Generated by Django 3.2.8 on 2021-10-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20211011_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[(1, 'Work'), (2, 'Event'), (3, 'Appointment'), (4, 'Habit')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='emergency',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
