# Generated by Django 3.2.8 on 2021-10-31 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20211031_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
